<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <StrawberryRoot>$(MSBuildThisFileDirectory)</StrawberryRoot>
    <StrawberryRootFwd>$(StrawberryRoot.Replace('\', '/'))</StrawberryRootFwd>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <!-- 모든 프로젝트 공통 -->
      <SDLCheck>true</SDLCheck>
      <ScanSourceForModuleDependencies>true</ScanSourceForModuleDependencies>
      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion> <!-- Assert 사용하기 위해서 인라인 함수확장을 /Ob1로 변경 -->

      <!-- CRT -->
      <RuntimeLibrary Condition="'$(Configuration)'=='Debug'">MultiThreadedDebugDLL</RuntimeLibrary>
      <RuntimeLibrary Condition="'$(Configuration)'=='Release'">MultiThreadedDLL</RuntimeLibrary>

      <!-- Common compiler options -->
      <AdditionalOptions>/utf-8 /Zc:__cplusplus /permissive- /MP %(AdditionalOptions)</AdditionalOptions>

      <!-- Common include -->
      <AdditionalIncludeDirectories>
        $(ProjectDir);
        $(StrawberryRoot);
	$(StrawberryRoot)Game;
        $(StrawberryRoot)Runtime;
        $(StrawberryRoot)ThirdParty\Include;
        $(StrawberryRoot)ThirdParty;
        %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>

    <Link>
      <AdditionalLibraryDirectories>
        $(StrawberryRoot)ThirdParty\Libs;
        %(AdditionalLibraryDirectories)
      </AdditionalLibraryDirectories>
    </Link>

  </ItemDefinitionGroup>
</Project>