<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\..'))" />
  <ItemDefinitionGroup>

    <ClCompile>
      <AdditionalIncludeDirectories>
        $(StrawberryRoot)ThirdParty\KTX\Include;
        %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>

  </ItemDefinitionGroup>
</Project>
