<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\..'))" />
  <ItemDefinitionGroup>

    <ClCompile>
      <PreprocessorDefinitions>
        SPDLOG_COMPILED_LIB;
        %(PreprocessorDefinitions)
      </PreprocessorDefinitions>
    </ClCompile>

  </ItemDefinitionGroup>
</Project>
